# Generated by Django 5.1.1 on 2024-11-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trending_movies'),
        ),
    ]
