# Generated by Django 5.1.1 on 2024-11-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_movies_films'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
