# Generated by Django 5.1.1 on 2024-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TRENDING', 'Trending'), ('ANIME', 'Anime'), ('INDIAN', 'Indian'), ('WEBSERIES', 'Webseries'), ('HOLLYWOOD', 'Hollywood')], max_length=20)),
                ('mov_vi_ori', models.CharField(default='Movie Vista Original', max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('re_year', models.IntegerField()),
                ('imdb', models.CharField(default='IMDB', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('starcast', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(upload_to='movie_images')),
                ('video', models.FileField(upload_to='movie_videos')),
            ],
        ),
    ]
