# Generated by Django 5.1.1 on 2024-12-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('CAROUSEL', 'Carousel'), ('TRENDING', 'Trending'), ('ANIME', 'Anime'), ('INDIAN', 'Indian'), ('WEBSERIES', 'Webseries'), ('HOLLYWOOD', 'Hollywood')], max_length=20),
        ),
    ]
