# Generated by Django 5.1.1 on 2024-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='category',
            field=models.CharField(choices=[('CAROUSEL', 'carousel'), ('TRENDING', 'trending'), ('ANIME', 'anime'), ('WEBSERIES', 'webseries'), ('INDIAN_MOVIES', 'indian_movies'), ('HOLLYWOOD_MOVIES', 'hollywood_movies')], default='Trending', max_length=20),
        ),
    ]
