# Generated by Django 5.1.1 on 2024-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_movies',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='carousel_movies',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='carousel_movies',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='carousel_movies',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='indian_movies',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='indian_movies',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='indian_movies',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='trending_movies',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='trending_movies',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='trending_movies',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='webseries',
            name='director',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='webseries',
            name='producers',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='webseries',
            name='starcast',
            field=models.CharField(default=2, max_length=200),
        ),
    ]
