# Generated by Django 5.1.1 on 2024-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('movie_duration', models.TimeField()),
                ('description', models.TextField()),
                ('movie_image', models.ImageField(upload_to='movie_images')),
            ],
        ),
    ]
