# Generated by Django 5.1.1 on 2024-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvel',
            name='email',
        ),
        migrations.AddField(
            model_name='marvel',
            name='heroic_name',
            field=models.CharField(default='Ironman', max_length=50),
        ),
    ]
