# Generated by Django 5.1.1 on 2024-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_marvel_email_marvel_heroic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvel',
            name='heroic_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
