# Generated by Django 5.1.1 on 2024-11-28 17:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(default='name', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
