# Generated by Django 5.1.1 on 2024-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_movies',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carousel_movies',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indian_movies',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trending_movies',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
