# Generated by Django 5.1.1 on 2024-12-08 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_movies_movie_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_cart',
            new_name='Watchlist',
        ),
    ]
